# Build and activate the current configuration.
apply ARGS="":
    darwin-rebuild switch --flake '.#jrh' {{ARGS}}
    # Set default shell, until this is resolved: https://github.com/LnL7/nix-darwin/issues/1237
    if [[ "$SHELL" != *fish* ]]; then chsh -s /run/current-system/sw/bin/fish; fi

update:
    nix flake update
    just switch

diff-plists:
  echo "Reading current settings..."
  defaults read >/tmp/settings-before.txt
  read -r -p "Toggle your setting and press any key..."
  echo "Reading updated settings..."
  defaults read >/tmp/settings-after.txt
  nvim -d /tmp/settings-before.txt /tmp/settings-after.txt
  rm /tmp/settings-before.txt /tmp/settings-after.txt
