"$schema" = 'https://jj-vcs.github.io/jj/latest/config-schema.json'

[aliases]
logr = ["log", "--reversed"]
logrt = ["log", "--reversed", "-r", "trunk()::"]

[git]
fetch = ["regex:^(origin|upstream)$"]
private-commits = "description(glob:'wip:*')" # Prevent pushing commits with these descriptions
sign-on-push = true

[revset-aliases]
branch = "trunk()..@"
branches = "trunk() | trunk()..visible_heads()"
open = "mine() ~ ::trunk()"

[signing]
backend = "ssh"
backends.ssh.allowed-signers = "~/.ssh/pubkeys/signers"
key = "~/.ssh/pubkeys/github.pub"

[templates]
commit_trailers = 'format_signed_off_by_trailer(self)'

[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[ui]
default-command = ["log", "--reversed", "-r", "trunk()..@"]
diff-formatter = ":git"
pager = "delta"
show-cryptographic-signatures = true

[ui.movement]
edit = true # Default `jj {prev,next}` to `--edit`

[user]
name = "Jacob Hayes"
email = "jrh@jacobhayes.dev"
