"$schema" = 'https://jj-vcs.github.io/jj/latest/config-schema.json'

[aliases]
logr = ["log", "--reversed"]
logrt = ["log", "--reversed", "-r", "trunk()::"]
rebase-open = ["rebase", "-s", "all:roots(trunk()..open)", "-d", "trunk()"]

[git]
private-commits = "description(glob:'wip:*')" # Prevent pushing commits with these descriptions
sign-on-push = true

[revset-aliases]
branches = "trunk() | trunk()..visible_heads()"
open = "trunk() | (mine() ~ ::trunk())"         # https://github.com/jj-vcs/jj/issues/2943#issuecomment-1925849130

[signing]
backend = "ssh"
backends.ssh.allowed-signers = "~/.ssh/pubkeys/signers"
key = "~/.ssh/pubkeys/github.pub"

[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[ui]
default-command = ["log", "--reversed", "-r", "trunk()..@"]
diff-editor = ":builtin"
merge-editor = ":builtin"
pager = "delta"
show-cryptographic-signatures = true

[ui.diff]
format = "git"

[ui.movement]
edit = true # Default `jj {prev,next}` to `--edit`

[user]
name = "Jacob Hayes"
email = "jrh@jacobhayes.dev"
